'use client'
import Head from 'next/head';
import '../styles/globals.css';
import Footer from './components/Footer';
import NavBar from "./components/NavBar";
import {AuthContextProvider} from './firebase/auth/AuthContext'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const metadata = {
  //   title: "Gym-Bro",
  //   description: "Generated by Next.js",
  // };
  return (
    <html lang="en">
      {/* <header>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </header> */}
      <body>      
        <AuthContextProvider>
        <NavBar />
          {children}
        </AuthContextProvider>
        <Footer />
        </body>
    </html>
  );
}