import '../styles/globals.css';
import Footer from './components/Footer';
import NavBar from "./components/NavBar";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
export const metadata = {
  title: "Gym-Bro",
  description: "Generated by Next.js",
};